In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib as plt
print(torch.__version__)

2.1.2+cu121


In [4]:
scalar = torch.tensor(8)
scalar

tensor(8)

In [5]:
scalar.ndim

0

In [6]:
scalar.item()

8

In [9]:
vector = torch.tensor([7, 7])
vector, vector.shape

(tensor([7, 7]), torch.Size([2]))

In [10]:
vector.ndim

1

In [12]:
matrix = torch.tensor([[7, 8],
                       [9, 10]])
matrix

tensor([[ 7,  8],
        [ 9, 10]])

In [14]:
matrix.ndim, matrix.shape

(2, torch.Size([2, 2]))

In [17]:
tensor = torch.tensor([[[1, 2, 3,],
         [4, 5, 6],
         [7, 8, 9]]])
tensor.shape, tensor.ndim

(torch.Size([1, 3, 3]), 3)

In [18]:
random_tensor = torch.rand(size=(3, 4))
random_tensor

tensor([[0.9874, 0.4902, 0.1714, 0.8098],
        [0.8586, 0.8378, 0.1355, 0.6656],
        [0.5555, 0.6244, 0.2821, 0.7699]])

In [19]:
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [20]:
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [23]:
zero_to_ten_deprecated = torch.range(0, 10)
zero_to_ten = torch.arange(0, 10, step=2)
zero_to_ten_deprecated, zero_to_ten

/tmp/ipykernel_16226/2719637970.py:1: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = torch.range(0, 10)


(tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.]),
 tensor([0, 2, 4, 6, 8]))

In [27]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=torch.float32,
                               device='cuda',
                               requires_grad=False)
float_32_tensor

tensor([3., 6., 9.], device='cuda:0')

In [29]:
float_16_tensor = torch.tensor([3, 6, 9],
                               dtype=torch.float16,
                               device='cuda',
                               requires_grad=False)
float_16_tensor

tensor([3., 6., 9.], device='cuda:0', dtype=torch.float16)

In [30]:
some_tensor = torch.rand(3, 4)
some_tensor.shape, some_tensor.dtype, some_tensor.device

(torch.Size([3, 4]), torch.float32, device(type='cpu'))

In [31]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor+10

(tensor([1, 2, 3]), tensor([11, 12, 13]))

In [33]:
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [35]:
tensor * tensor

tensor([1, 4, 9])

In [36]:
tensor @ tensor

tensor(14)

In [38]:
torch.matmul(tensor, tensor)

tensor(14)

In [39]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 507 µs, sys: 119 µs, total: 626 µs
Wall time: 445 µs


tensor(14)

In [40]:
%%time
tensor @ tensor

CPU times: user 230 µs, sys: 54 µs, total: 284 µs
Wall time: 201 µs


tensor(14)

In [42]:
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A.T, tensor_B)

tensor([[ 76., 103.],
        [100., 136.]])

In [43]:
torch.mm(tensor_A.T, tensor_B)

tensor([[ 76., 103.],
        [100., 136.]])

In [45]:
torch.manual_seed(42)
linear = torch.nn.Linear(in_features=2,
                         out_features=6)
x = tensor_A
output = linear(x)
print(f"Input: {x}")
print(f"Output: {output}")

Input: tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
Output: tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)


In [47]:
x = torch.arange(0, 100, 10)
print(f"min: {x.min()}, max: {x.max()}, mean: {x.type(torch.float32).mean()}, sum: {x.sum()}")

min: 0, max: 90, mean: 45.0, sum: 450


In [50]:
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")
print(f"max: {tensor.argmax()}")
print(f"min: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
max: 8
min: 0


In [51]:
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [52]:
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

In [54]:
x = torch.arange(1., 8.)
x, x.shape, x.type

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]), <function Tensor.type>)

In [64]:
import torch
x = torch.arange(1., 8.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7.]), torch.Size([7]))

In [66]:
x_reshaped = x.reshape(1, 7)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7.]]), torch.Size([1, 7]))

In [67]:
x_reshaped.reshape(7, 1)

tensor([[1.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.]])

In [70]:
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.],
        [1., 2., 3., 4., 5., 6., 7.]])

In [71]:
x_stacked.ndim

2

In [79]:
x_squeezed = x_reshaped.squeeze()
x_squeezed

tensor([1., 2., 3., 4., 5., 6., 7.])

In [81]:
x_original = torch.rand(size=(224, 224, 3))
x_permuted = x_original.permute(2, 0, 1)
x_original.shape, x_permuted.shape

(torch.Size([224, 224, 3]), torch.Size([3, 224, 224]))

In [83]:
x = torch.arange(1, 10).reshape(1, 3, 3)
x

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [84]:
x[0], x[0][0], x[0][0][0]

(tensor([[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]),
 tensor([1, 2, 3]),
 tensor(1))

In [85]:
# all values of 9th dimension and the 0 index
x[:, 0]

tensor([[1, 2, 3]])

In [89]:
# all values of the 0 dimension but only the 1 index value of the 1 st and 2 dimnsion
x[:, 1, 1]

tensor([5])

In [90]:
# 0 of 0th and 1st dimension and all values fo 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [95]:
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [96]:
array = array + 1
array

array([2., 3., 4., 5., 6., 7., 8.])

In [106]:
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [107]:
tensor = tensor +  1
numpy_tensor = numpy_tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([2., 2., 2., 2., 2., 2., 2.], dtype=float32))

In [108]:
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

random_tensor_A, random_tensor_B, random_tensor_A == random_tensor_B

(tensor([[0.8660, 0.2001, 0.7926, 0.1140],
         [0.6855, 0.0086, 0.3588, 0.9211],
         [0.8627, 0.8223, 0.5248, 0.5881]]),
 tensor([[0.2746, 0.3791, 0.2975, 0.6450],
         [0.0163, 0.9160, 0.5888, 0.8403],
         [0.4761, 0.7140, 0.4644, 0.6362]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [110]:
random_seed = 42

torch.manual_seed(seed=random_seed)
random_tensor_C = torch.rand(3, 4)
torch.manual_seed(seed=random_seed)
random_tensor_D = torch.rand(3, 4)

random_tensor_C, random_tensor_D

(tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]),
 tensor([[0.8823, 0.9150, 0.3829, 0.9593],
         [0.3904, 0.6009, 0.2566, 0.7936],
         [0.9408, 0.1332, 0.9346, 0.5936]]))

In [111]:
torch.cuda.is_available()

True

In [112]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [114]:
torch.cuda.device_count()

1

In [115]:
tensor = torch.tensor([1, 2, 3])
tensor, tensor.device

(tensor([1, 2, 3]), device(type='cpu'))

In [116]:
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

In [120]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])