In [1]:
import torch

In [2]:
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [3]:
my_tensor = torch.tensor([[1, 2, 3], [4, 5, 6]], dtype=torch.float32,
                  device=device, requires_grad=True)

print(my_tensor)
print(my_tensor.dtype)
print(my_tensor.device)
print(my_tensor.shape)
print(my_tensor.requires_grad)

tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0', requires_grad=True)
torch.float32
cuda:0
torch.Size([2, 3])
True


In [4]:
x_empty = torch.empty(size = (3, 3))
x_empty

tensor([[-7.5671e-09,  1.5667e-42,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00],
        [ 0.0000e+00,  0.0000e+00,  0.0000e+00]])

In [5]:
x_zeros = torch.zeros(3, 3)
x_zeros

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [6]:
x_rand = torch.rand((3, 3))
x_rand

tensor([[0.9896, 0.6797, 0.6015],
        [0.8334, 0.9971, 0.5035],
        [0.7661, 0.0675, 0.0246]])

In [7]:
x_ones = torch.ones((3, 3))
x_ones

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [8]:
x = torch.eye(5, 5) 
x

tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])

In [9]:
x_arange = torch.arange(start=0, end=10, step=2)
print(x_arange)

tensor([0, 2, 4, 6, 8])


In [10]:
x_linspace = torch.linspace(start=0.1, end=1, steps=10)
x_linspace

tensor([0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000, 0.9000,
        1.0000])

In [17]:
x = torch.empty(size=(1, 5)).normal_(mean=0, std=1)  # 1x5 tensor
x

tensor([[-0.0956, -0.4679,  0.3289, -0.8082,  0.0305]])

In [21]:
x = torch.empty(size=(1, 5)).uniform_(0, 1)
x

tensor([[0.5506, 0.5201, 0.0889, 0.1073, 0.6268]])

In [22]:
torch.diag(torch.ones(3))

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [23]:
torch.eye(3,3)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])

In [27]:
# Hot to initialize and convert tensors to other types
tensor = torch.arange(4)
tensor

tensor([0, 1, 2, 3])

In [25]:
print(tensor.bool())

tensor([False,  True,  True,  True])


In [28]:
print(tensor.short())

tensor([0, 1, 2, 3], dtype=torch.int16)


In [35]:
print(tensor.long(), " ", tensor.long().dtype)

tensor([0, 1, 2, 3])   torch.int64


In [36]:
print(tensor.half())

tensor([0., 1., 2., 3.], dtype=torch.float16)
